language: python
cache: false
python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - CONDA_DEPS="pytest coverage coveralls pytest-cov numpy"

before_install:
  - sudo apt-get update
  # Here we download miniconda and install the dependencies
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -f -p $MINICONDA
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
  - source activate testenv

install:
    - python setup.py install

script:
  - coverage run --source tudaesasII -m py.test
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change

